language: python
python:
  - 2.7
install:
  - curl -s -o google_appengine.zip https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.7.zip && unzip -q google_appengine.zip
script: PYTHONPATH=`pwd`/google_appengine:`pwd`/google_appengine/lib/yaml/lib python setup.py test
